# Cut a release whenever a new tag is pushed to the repo.
# You should use an annotated tag, like `git tag -a v1.2.3`
# and put the release notes into the commit message for the tag.
name: Release

on:
  schedule:
    - cron: '30 10 * * 1' # every Monday at 00:00 UTC
  workflow_dispatch:

permissions: {}

jobs:
  gh-release:
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Calculate version bump
        id: create_tag
        uses: chainguard-dev/actions/git-tag@cd899cc96227b82170571cad1c3d6378d8cba678 # v1.4.15
        with:
          bump_level: patch
          dry_run: true
          use-gitsign: false

      - name: Create immutable source code release with tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TAG=${{ steps.create_tag.outputs.git_tag }}
          PREFIX="rules_apko-${TAG#v}"
          ARCHIVE="rules_apko-$TAG.tar.gz"
          git archive --format=tar.gz --prefix=${PREFIX}/ ${{ github.sha }} > $ARCHIVE
          gh release create ${TAG} --fail-on-no-commits --target ${{ github.sha }} --generate-notes $ARCHIVE

      - uses: octo-sts/action@main
        id: octo-sts
        with:
          scope: xnox/bazel-central-registry
          identity: release-rules-apko2

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: xnox/bazel-central-registry
          token: ${{ steps.octo-sts.outputs.token }}
          path: bazel-central-registry

      - working-directory: bazel-central-registry
        run: |
          git remote add upstream https://github.com/chainguard-dev/bazel-central-registry
          git remote update upstream
          git config remote."upstream".gh-resolved base
          branch="rules_apko-${{ steps.create_tag.outputs.git_tag }}"
          git checkout -b rules_apko-${{ steps.create_tag.outputs.git_tag }} upstream/main
          git config branch."$branch".pushremote origin

      - name: Create final entry
        id: create-final-entry
        uses: bazel-contrib/publish-to-bcr@301f65edec7118166379e2ef5f29a05d2868a449
        with:
          tag: ${{ steps.create_tag.outputs.git_tag }}
          module-version: ${{ steps.create_tag.outputs.bumped_version }}
          local-registry: bazel-central-registry
          templates-dir: .bcr

      - uses: chainguard-dev/actions/setup-gitsign@cd899cc96227b82170571cad1c3d6378d8cba678 # v1.4.15

      - name: Create PR
        env:
          GH_TOKEN: ${{ steps.octo-sts.outputs.token }}
        working-directory: bazel-central-registry
        run: |
          set -o errexit -o nounset -o pipefail
          git add .
          git commit -m "${{ steps.create-final-entry.outputs.short-description }}"
          git push origin `git branch --show-current`
          gh pr create --repo chainguard-dev/bazel-central-registry --base main --head xnox:`git branch --show-current` --fill-verbose --draft
